knpu_oauth2_client:
    clients:
        altered_reunion:
            type: keycloak
            client_id: '%env(KEYCLOAK_CLIENT_ID)%'
            client_secret: '%env(KEYCLOAK_CLIENT_SECRET)%'
            redirect_route: oauth_altered_reunion_callback
            redirect_params: {}
            auth_server_url: '%env(KEYCLOAK_BASE_URL)%'
            realm: '%env(KEYCLOAK_REALM)%'
