<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260111114917 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create registrations table for tournament player registrations';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE registrations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, decklist_url VARCHAR(255) DEFAULT NULL, registered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tournament_id INT NOT NULL, player_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_registrations_tournament ON registrations (tournament_id)');
        $this->addSql('CREATE INDEX idx_registrations_player ON registrations (player_id)');
        $this->addSql('CREATE INDEX idx_registrations_registered_at ON registrations (registered_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_registration_tournament_player ON registrations (tournament_id, player_id)');
        $this->addSql('ALTER TABLE registrations ADD CONSTRAINT FK_53DE51E733D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournaments (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE registrations ADD CONSTRAINT FK_53DE51E799E6F5DF FOREIGN KEY (player_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE registrations DROP CONSTRAINT FK_53DE51E733D1A3E7');
        $this->addSql('ALTER TABLE registrations DROP CONSTRAINT FK_53DE51E799E6F5DF');
        $this->addSql('DROP TABLE registrations');
    }
}
