<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260111111311 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tournaments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, date DATE NOT NULL, time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, entry_fee VARCHAR(50) DEFAULT NULL, prizes TEXT DEFAULT NULL, altered_gg_link VARCHAR(255) DEFAULT NULL, format VARCHAR(20) NOT NULL, structure VARCHAR(30) NOT NULL, visibility VARCHAR(10) NOT NULL, decklist_transparency VARCHAR(10) NOT NULL, status VARCHAR(15) NOT NULL, swiss_match_format VARCHAR(5) NOT NULL, elimination_match_format VARCHAR(5) DEFAULT NULL, swiss_rounds SMALLINT DEFAULT NULL, expected_players SMALLINT DEFAULT NULL, top_cut_size SMALLINT DEFAULT NULL, registrations_closed BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, organizer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_tournaments_status ON tournaments (status)');
        $this->addSql('CREATE INDEX idx_tournaments_organizer ON tournaments (organizer_id)');
        $this->addSql('CREATE INDEX idx_tournaments_visibility ON tournaments (visibility)');
        $this->addSql('CREATE INDEX idx_tournaments_date ON tournaments (date)');
        $this->addSql('ALTER TABLE tournaments ADD CONSTRAINT FK_E4BCFAC3876C4DDA FOREIGN KEY (organizer_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reset_password_requests ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE reset_password_requests ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN reset_password_requests.requested_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN reset_password_requests.expires_at IS \'\'');
        $this->addSql('ALTER INDEX idx_27e44f8a76ed395 RENAME TO IDX_16646B41A76ED395');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE users ALTER roles DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER is_verified DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.updated_at IS \'\'');
        $this->addSql('DROP INDEX idx_75ea56e016ba31db');
        $this->addSql('DROP INDEX idx_75ea56e0fb7336f0');
        $this->addSql('DROP INDEX idx_75ea56e0e3bd61ce');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'\'');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tournaments DROP CONSTRAINT FK_E4BCFAC3876C4DDA');
        $this->addSql('DROP TABLE tournaments');
        $this->addSql('DROP INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT nextval(\'messenger_messages_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX idx_75ea56e016ba31db ON messenger_messages (delivered_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX idx_75ea56e0e3bd61ce ON messenger_messages (available_at)');
        $this->addSql('ALTER TABLE reset_password_requests ALTER id SET DEFAULT nextval(\'reset_password_requests_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE reset_password_requests ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN reset_password_requests.requested_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reset_password_requests.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_16646b41a76ed395 RENAME TO idx_27e44f8a76ed395');
        $this->addSql('ALTER TABLE users ALTER id SET DEFAULT nextval(\'users_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE users ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE users ALTER roles SET DEFAULT \'["ROLE_USER"]\'');
        $this->addSql('ALTER TABLE users ALTER is_verified SET DEFAULT false');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.updated_at IS \'(DC2Type:datetime_immutable)\'');
    }
}
