<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260114085032 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add GROUP_STAGE_ELIMINATION tournament format: groups table, group configuration, and elimination round tracking';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tournament_groups (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, group_name VARCHAR(50) NOT NULL, group_letter VARCHAR(1) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tournament_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_tournament_groups_tournament ON tournament_groups (tournament_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_group_tournament_letter ON tournament_groups (tournament_id, group_letter)');
        $this->addSql('CREATE TABLE tournament_group_players (group_id INT NOT NULL, registration_id INT NOT NULL, PRIMARY KEY (group_id, registration_id))');
        $this->addSql('CREATE INDEX IDX_22D06117FE54D947 ON tournament_group_players (group_id)');
        $this->addSql('CREATE INDEX IDX_22D06117833D8F43 ON tournament_group_players (registration_id)');
        $this->addSql('ALTER TABLE tournament_groups ADD CONSTRAINT FK_94C7C72033D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournaments (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tournament_group_players ADD CONSTRAINT FK_22D06117FE54D947 FOREIGN KEY (group_id) REFERENCES tournament_groups (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tournament_group_players ADD CONSTRAINT FK_22D06117833D8F43 FOREIGN KEY (registration_id) REFERENCES registrations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE matches ADD group_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT FK_62615BAFE54D947 FOREIGN KEY (group_id) REFERENCES tournament_groups (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_62615BAFE54D947 ON matches (group_id)');
        $this->addSql('ALTER TABLE rounds ADD is_elimination_round BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE rounds ADD group_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE rounds ADD CONSTRAINT FK_3A7FD554FE54D947 FOREIGN KEY (group_id) REFERENCES tournament_groups (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_3A7FD554FE54D947 ON rounds (group_id)');
        $this->addSql('ALTER TABLE tournaments ADD group_count SMALLINT DEFAULT NULL');
        $this->addSql('ALTER TABLE tournaments ADD players_per_group SMALLINT DEFAULT NULL');
        $this->addSql('ALTER TABLE tournaments ADD qualifiers_per_group SMALLINT DEFAULT NULL');
        $this->addSql('ALTER TABLE tournaments ADD group_formation_method VARCHAR(20) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tournament_groups DROP CONSTRAINT FK_94C7C72033D1A3E7');
        $this->addSql('ALTER TABLE tournament_group_players DROP CONSTRAINT FK_22D06117FE54D947');
        $this->addSql('ALTER TABLE tournament_group_players DROP CONSTRAINT FK_22D06117833D8F43');
        $this->addSql('DROP TABLE tournament_groups');
        $this->addSql('DROP TABLE tournament_group_players');
        $this->addSql('ALTER TABLE matches DROP CONSTRAINT FK_62615BAFE54D947');
        $this->addSql('DROP INDEX IDX_62615BAFE54D947');
        $this->addSql('ALTER TABLE matches DROP group_id');
        $this->addSql('ALTER TABLE rounds DROP CONSTRAINT FK_3A7FD554FE54D947');
        $this->addSql('DROP INDEX IDX_3A7FD554FE54D947');
        $this->addSql('ALTER TABLE rounds DROP is_elimination_round');
        $this->addSql('ALTER TABLE rounds DROP group_id');
        $this->addSql('ALTER TABLE tournaments DROP group_count');
        $this->addSql('ALTER TABLE tournaments DROP players_per_group');
        $this->addSql('ALTER TABLE tournaments DROP qualifiers_per_group');
        $this->addSql('ALTER TABLE tournaments DROP group_formation_method');
    }
}
