<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260225110535 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add API access requests and credentials tables';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE api_access_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, project_name VARCHAR(100) NOT NULL, intended_use TEXT NOT NULL, website_url VARCHAR(255) DEFAULT NULL, discord_username VARCHAR(100) DEFAULT NULL, status VARCHAR(20) NOT NULL, rejection_reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, reviewed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AAD2F49FC6B21F1 ON api_access_requests (reviewed_by_id)');
        $this->addSql('CREATE INDEX idx_api_access_requests_status ON api_access_requests (status)');
        $this->addSql('CREATE INDEX idx_api_access_requests_user ON api_access_requests (user_id)');
        $this->addSql('CREATE INDEX idx_api_access_requests_created_at ON api_access_requests (created_at)');
        $this->addSql('CREATE TABLE api_credentials (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, api_key VARCHAR(64) NOT NULL, name VARCHAR(100) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, request_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9072A280427EB8A5 ON api_credentials (request_id)');
        $this->addSql('CREATE INDEX idx_api_credentials_user ON api_credentials (user_id)');
        $this->addSql('CREATE INDEX idx_api_credentials_active ON api_credentials (is_active)');
        $this->addSql('CREATE UNIQUE INDEX uniq_api_credentials_api_key ON api_credentials (api_key)');
        $this->addSql('ALTER TABLE api_access_requests ADD CONSTRAINT FK_3AAD2F49A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE api_access_requests ADD CONSTRAINT FK_3AAD2F49FC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE api_credentials ADD CONSTRAINT FK_9072A280A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE api_credentials ADD CONSTRAINT FK_9072A280427EB8A5 FOREIGN KEY (request_id) REFERENCES api_access_requests (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE api_access_requests DROP CONSTRAINT FK_3AAD2F49A76ED395');
        $this->addSql('ALTER TABLE api_access_requests DROP CONSTRAINT FK_3AAD2F49FC6B21F1');
        $this->addSql('ALTER TABLE api_credentials DROP CONSTRAINT FK_9072A280A76ED395');
        $this->addSql('ALTER TABLE api_credentials DROP CONSTRAINT FK_9072A280427EB8A5');
        $this->addSql('DROP TABLE api_access_requests');
        $this->addSql('DROP TABLE api_credentials');
    }
}
