<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates notifications table for tournament reminders (FR64-FR67).
 */
final class Version20260111140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create notifications table for tournament reminders (FR64-FR67)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE notifications (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            tournament_id INT NOT NULL,
            type VARCHAR(20) NOT NULL,
            status VARCHAR(10) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            error_message TEXT DEFAULT NULL,
            round_number SMALLINT DEFAULT NULL,
            PRIMARY KEY(id)
        )');

        $this->addSql('COMMENT ON COLUMN notifications.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifications.sent_at IS \'(DC2Type:datetime_immutable)\'');

        $this->addSql('CREATE INDEX idx_notifications_user ON notifications (user_id)');
        $this->addSql('CREATE INDEX idx_notifications_tournament ON notifications (tournament_id)');
        $this->addSql('CREATE INDEX idx_notifications_type_status ON notifications (type, status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_tournament_type ON notifications (user_id, tournament_id, type)');

        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D333D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournaments (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D333D1A3E7');
        $this->addSql('DROP TABLE notifications');
    }
}
