<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260111125001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create rounds and matches tables for tournament pairings';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE matches (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, table_number INT NOT NULL, result JSON DEFAULT NULL, status VARCHAR(20) NOT NULL, is_bye BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, round_id INT NOT NULL, player1_id INT NOT NULL, player2_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_matches_round ON matches (round_id)');
        $this->addSql('CREATE INDEX idx_matches_status ON matches (status)');
        $this->addSql('CREATE INDEX idx_matches_player1 ON matches (player1_id)');
        $this->addSql('CREATE INDEX idx_matches_player2 ON matches (player2_id)');
        $this->addSql('CREATE TABLE rounds (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, round_number INT NOT NULL, status VARCHAR(20) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tournament_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_rounds_tournament ON rounds (tournament_id)');
        $this->addSql('CREATE INDEX idx_rounds_status ON rounds (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_rounds_tournament_number ON rounds (tournament_id, round_number)');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT FK_62615BAA6005CA0 FOREIGN KEY (round_id) REFERENCES rounds (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT FK_62615BAC0990423 FOREIGN KEY (player1_id) REFERENCES registrations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT FK_62615BAD22CABCD FOREIGN KEY (player2_id) REFERENCES registrations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rounds ADD CONSTRAINT FK_3A7FD55433D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournaments (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE matches DROP CONSTRAINT FK_62615BAA6005CA0');
        $this->addSql('ALTER TABLE matches DROP CONSTRAINT FK_62615BAC0990423');
        $this->addSql('ALTER TABLE matches DROP CONSTRAINT FK_62615BAD22CABCD');
        $this->addSql('ALTER TABLE rounds DROP CONSTRAINT FK_3A7FD55433D1A3E7');
        $this->addSql('DROP TABLE matches');
        $this->addSql('DROP TABLE rounds');
    }
}
