<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260111131709 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add match_submissions table for result tracking and dispute_history to matches';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE match_submissions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, claimed_winner_id INT NOT NULL, player1_score INT NOT NULL, player2_score INT NOT NULL, game_details JSON DEFAULT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, match_id INT NOT NULL, submitted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON COLUMN match_submissions.submitted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX idx_submissions_match ON match_submissions (match_id)');
        $this->addSql('CREATE INDEX idx_submissions_submitted_by ON match_submissions (submitted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_submission_match_player ON match_submissions (match_id, submitted_by_id)');
        $this->addSql('ALTER TABLE match_submissions ADD CONSTRAINT FK_DF818DF2ABEACD6 FOREIGN KEY (match_id) REFERENCES matches (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE match_submissions ADD CONSTRAINT FK_DF818DF79F7D87D FOREIGN KEY (submitted_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE matches ADD dispute_history JSON DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE match_submissions DROP CONSTRAINT FK_DF818DF2ABEACD6');
        $this->addSql('ALTER TABLE match_submissions DROP CONSTRAINT FK_DF818DF79F7D87D');
        $this->addSql('DROP TABLE match_submissions');
        $this->addSql('ALTER TABLE matches DROP dispute_history');
    }
}
