<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260123103123 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create contact_reports table for user feedback and bug reports';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contact_reports (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subject VARCHAR(20) NOT NULL, message TEXT NOT NULL, page_url VARCHAR(500) DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6B3086C4A76ED395 ON contact_reports (user_id)');
        $this->addSql('CREATE INDEX idx_contact_reports_status ON contact_reports (status)');
        $this->addSql('CREATE INDEX idx_contact_reports_created_at ON contact_reports (created_at)');
        $this->addSql('ALTER TABLE contact_reports ADD CONSTRAINT FK_6B3086C4A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE contact_reports DROP CONSTRAINT FK_6B3086C4A76ED395');
        $this->addSql('DROP TABLE contact_reports');
    }
}
